# Numpy cheat sheet

**Disclaimer**: this course is adapted from the work by Nicolas Rougier: [https://github.com/rougier/numpy-tutorial](https://github.com/rougier/numpy-tutorial).


Let us start with a preliminary remark concerning the random part.
One is expected to run a command like
```Python
import numpy as np
rng = np.random.default_rng(12)
```
before anything, to initialize the random generator `rng`.

## Matrix creation

### Creation: vector case

<head>
<style>
table {
    border: border-collapse;
    margin-left: auto;
    margin-right: auto;
}

th, td {
  text-align: left;
  padding: 8px;
}

tr:nth-child(even) {background-color: #f2f2f2;}

td {
    border: solid 1px #dbe1e6;

}
th {
    border: solid 1px #dbe1e6;

}
thead,th {border: 1px solid #dbe1e6;}
thead,th {text-align: center;}

</style>
</head>

<table>
  <thead>
    <tr>
      <th>Code</th>
      <th>Result</th>
    </tr>
  </thead>
  <tbody>
  <tr>
        <td> <pre> x = np.zeros(9) </pre> </td>
        <td style="text-align: center; vertical-align: middle;"> <image src = "../ScipyNumpy/CheatSheet/figures/create-zeros-1.svg" width=60%"></image> </td>
    </tr>
    <tr>
        <td> <pre> x = np.ones(9)</pre> </td>
        <td style="text-align: center; vertical-align: middle;"> <image src = "../ScipyNumpy/CheatSheet/figures/create-ones-1.svg" width=60%"></image> </td>
    </tr>
    <tr>
        <td> <pre> x = np.full(9, 0.5)</pre> </td>
        <td style="text-align: center; vertical-align: middle;"> <image src = "../ScipyNumpy/CheatSheet/figures/create-full-1.svg" width=60%"></image> </td>
    </tr>
    <tr>
        <td>
        <pre> x = np.zeros(9)
 x[2] = 1
        </pre></td>
        <td style="text-align: center; vertical-align: middle;"> <image src = "../ScipyNumpy/CheatSheet/figures/create-list-1.svg" width=60%"></image> </td>
    </tr>
    <tr>
        <td> <pre> x = np.arange(9)</pre> </td>
        <td style="text-align: center; vertical-align: middle;"> <image src = "../ScipyNumpy/CheatSheet/figures/create-arange-1.svg" width=60%"></image> </td>
    </tr>
    <tr>
        <td> <pre> x[::-1]</pre> </td>
        <td style="text-align: center; vertical-align: middle;"> <image src = "../ScipyNumpy/CheatSheet/figures/create-arange-1-backward.svg" width=60%"></image> </td>
    </tr>
    <tr>
        <td> <pre> x = rng.random(9)</pre> </td>
        <td style="text-align: center; vertical-align: middle;"> <image src = "../ScipyNumpy/CheatSheet/figures/create-uniform-1.svg" width=60%"></image> </td>
    </tr>
  </tbody>
</table>


### Creation: matrix case

<table>
  <thead>
    <tr>
      <th>Code</th>
      <th>Result</th>
    </tr>
  </thead>
  <tbody>
        <tr>
            <td> <pre> M = np.zeros((5, 9)) </pre> </td>
            <td style="text-align: center; vertical-align: middle;"> <image src = "../ScipyNumpy/CheatSheet/figures/create-zeros-2.svg" width="54%"></image> </td>
        </tr>
        <tr>
            <td> <pre> M = np.ones((5, 9))</pre> </td>
            <td style="text-align: center; vertical-align: middle;"> <image src = "../ScipyNumpy/CheatSheet/figures/create-ones-2.svg" width="54%"></image> </td>
        </tr>
        <tr>
            <td> <pre> M = np.zeros((5, 9))
 M[0, 2] = 0.5
 M[1, 0] = 1.
 M[2, 1] = 0.4
            </pre> </td>
            <td style="text-align: center; vertical-align: middle;"> <image src = "../ScipyNumpy/CheatSheet/figures/create-list-2.svg" width="54%"></image> </td>
        </tr>
        <tr>
            <td><pre> M = np.arange(45).reshape((5, 9))</pre> </td>
            <td style="text-align: center; vertical-align: middle;"> <image src = "../ScipyNumpy/CheatSheet/figures/create-arange-2.svg" width="54%"></i mage> </td>
        </tr>
        <tr>
            <td> <pre> M = rng.random((5, 9))</pre> </td>
            <td style="text-align: center; vertical-align: middle;"> <image src = "../ScipyNumpy/CheatSheet/figures/create-uniform-2.svg" width="54%"></image> </td>
        </tr>
        <tr>
            <td> <pre> M = np.eye(5, 9)</pre> </td>
            <td style="text-align: center; vertical-align: middle;"> <image src = "../ScipyNumpy/CheatSheet/figures/create-eye-2.svg" width="54%"></image> </td>
        </tr>
        <tr>
            <td> <pre> M = np.diag(np.arange(5))</pre> </td>
            <td> <center><image src = "../ScipyNumpy/CheatSheet/figures/create-diag-2.svg" width="30%"></image></center> </td>
        </tr>
        <tr>
            <td> <pre> M = np.diag(np.arange(3), k=2)</pre> </td>
            <td> <center><image src = "../ScipyNumpy/CheatSheet/figures/create-diagk-2.svg" width="30%"></image></center> </td>
        </tr>
    </tbody>
</table>



### Meshgrid (&#127467;&#127479;: maillage)

```Python
nx, ny = (8, 3)
x = np.linspace(0, 1, nx)
y = np.linspace(0, 1, ny)
xx, yy = np.meshgrid(x, y)
```

<table>
  <thead>
    <tr>
      <th>x</th>
      <th>y</th>
      <th>xx</th>
      <th>yy</th>
    </tr>
  </thead>
  <tbody>
        <tr>
            <td style="text-align: center; vertical-align: middle;"> <image src = "../ScipyNumpy/CheatSheet/figures/meshgrid-x.svg" width="90%"></image> </td>
            <td style="text-align: center; vertical-align: middle;"> <image src = "../ScipyNumpy/CheatSheet/figures/meshgrid-y.svg" width="30%"></image> </td>
            <td style="text-align: center; vertical-align: middle;"> <image src = "../ScipyNumpy/CheatSheet/figures/meshgrid-xv.svg" width="90%"></image> </td>
            <td style="text-align: center; vertical-align: middle;"> <image src = "../ScipyNumpy/CheatSheet/figures/meshgrid-yv.svg" width="90%"></image> </td>
        </tr>
    </tbody>
</table>

### Creation: tensor cases

<table>
  <thead>
    <tr>
      <th>Code</th>
      <th>Result</th>
    </tr>
  </thead>
  <tbody>
        <tr>
            <td> <pre> T = np.zeros((3, 5, 9)) </pre> </td>
            <td style="text-align: center; vertical-align: middle;"> <image src = "../ScipyNumpy/CheatSheet/figures/create-zeros-3.svg" width="70%"></image> </td>
        </tr>
        <tr>
            <td> <pre> T = np.ones((3, 5, 9))</pre> </td>
            <td style="text-align: center; vertical-align: middle;"> <image src = "../ScipyNumpy/CheatSheet/figures/create-ones-3.svg" width="70%"></image> </td>
        </tr>
        <tr>
            <td> <pre> T = np.arange(135).reshape(3, 5, 9)</pre> </td>
            <td style="text-align: center; vertical-align: middle;"> <image src = "../ScipyNumpy/CheatSheet/figures/create-arange-3.svg" width="70%"></image> </td>
        </tr>
        <tr>
            <td> <pre> T = rng.random((3, rows, cols))</pre> </td>
            <td style="text-align: center; vertical-align: middle;"> <image src = "../ScipyNumpy/CheatSheet/figures/create-uniform-3.svg" width="70%"></image> </td>
        </tr>
        <tr>
        <td>
        <pre>
<br>
n1, n2 = 5, 3
ones = np.ones((n2, n1))
ones = ones[:, :, np.newaxis]
lnsp = np.linspace(0.01, 0.99, 8)
T = ones * lnsp
        </pre>
        </td>
         <td style="text-align: center; vertical-align: middle;"> <image src = "../ScipyNumpy/CheatSheet/figures/create-increasing-slice.svg" width="40%"></image> </td>
        </tr>
    </tbody>
</table>

## Matrix reshaping

We start here with
```Python
M = np.zeros((3, 4))
M[2, 2] = 1
```

<center>
<image src = "../ScipyNumpy/CheatSheet/figures/reshape-M.svg" width="25%"></image>
</center>

Starting from the previous matrix, we can reshape it in different ways:

<table>
  <thead>
    <tr>
      <th>Code</th>
      <th>Result</th>
    </tr>
  </thead>
  <tbody>
        <tr>
            <td> <pre>M = M.reshape(4, 3)</pre> </td>
            <td style="text-align: center; vertical-align: middle;"> <image src = "../ScipyNumpy/CheatSheet/figures/reshape-M-reshape(4,3).svg" width="21%"></image> </td>
        </tr>
        <tr>
            <td> <pre>M = M.reshape(12, 1)</pre> </td>
            <td style="text-align: center; vertical-align: middle;"> <image src = "../ScipyNumpy/CheatSheet/figures/reshape-M-reshape(12,1).svg" width="7%"></image> </td>
        </tr>
        <tr>
            <td> <pre>M = M.reshape(1, 12)</pre> </td>
            <td style="text-align: center; vertical-align: middle;"> <image src = "../ScipyNumpy/CheatSheet/figures/reshape-M-reshape(1,12).svg" width="84%"></image> </td>
        </tr>
        <tr>
            <td> <pre>M = M.reshape(6, 2)</pre> </td>
            <td style="text-align: center; vertical-align: middle;"> <image src = "../ScipyNumpy/CheatSheet/figures/reshape-M-reshape(6,2).svg" width="14%"></image> </td>
        </tr>
        <tr>
            <td> <pre>M = M.reshape(2, 6)</pre> </td>
            <td style="text-align: center; vertical-align: middle;"> <image src = "../ScipyNumpy/CheatSheet/figures/reshape-M-reshape(2,6).svg" width="42%"></image> </td>
        </tr>
    </tbody>
</table>


## Slicing

Start from a zero matrix:
```Python
M = np.zeros((5, 9))
```

<center>
<image src = "../ScipyNumpy/CheatSheet/figures/slice-M.svg" width="25%"></image> 
</center>


Starting from the previous matrix, we can slice it in different ways:

<table>
  <thead>
    <tr>
      <th>Code</th>
      <th>Result</th>
    </tr>
  </thead>
  <tbody>
        <tr>
            <td> <pre>M[...] = 1 </pre> </td>
            <td style="text-align: center; vertical-align: middle;"> <image src = "../ScipyNumpy/CheatSheet/figures/slice-M[...].svg" width="59%"></image> </td>
        </tr>
        <tr>
            <td> <pre>M[:, ::2] = 1</pre> </td>
            <td style="text-align: center; vertical-align: middle;"> <image src = "../ScipyNumpy/CheatSheet/figures/slice-M[:,::2].svg" width="59%"></image> </td>
        </tr>
        <tr>
            <td> <pre>M[::2, :] = 1</pre> </td>
            <td style="text-align: center; vertical-align: middle;"> <image src = "../ScipyNumpy/CheatSheet/figures/slice-M[::2,:].svg" width="59%"></image> </td>
        </tr>
        <tr>
            <td> <pre>M[1, 1] = 1</pre> </td>
            <td style="text-align: center; vertical-align: middle;"> <image src = "../ScipyNumpy/CheatSheet/figures/slice-M[1,1].svg" width="59%"></image> </td>
        </tr>
        <tr>
            <td> <pre>M[:, 0] = 1</pre> </td>
            <td style="text-align: center; vertical-align: middle;"> <image src = "../ScipyNumpy/CheatSheet/figures/slice-M[:,0].svg" width="59%"></image> </td>
        </tr>
        <tr>
            <td> <pre>M[0, :] = 1</pre> </td>
            <td style="text-align: center; vertical-align: middle;"> <image src = "../ScipyNumpy/CheatSheet/figures/slice-M[0,:].svg" width="59%"></image> </td>
        </tr>
        <tr>
            <td> <pre>M[2:; 2:] = 1</pre> </td>
            <td style="text-align: center; vertical-align: middle;"> <image src = "../ScipyNumpy/CheatSheet/figures/slice-M[2:,2:].svg" width="59%"></image> </td>
        </tr>
        <tr>
            <td> <pre>M[:-2:, :-2] = 1</pre> </td>
            <td style="text-align: center; vertical-align: middle;"> <image src = "../ScipyNumpy/CheatSheet/figures/slice-M[:-2,:-2].svg" width="59%"></image> </td>
        </tr>
        <tr>
            <td> <pre>M[2:4, 2:4] = 1</pre> </td>
            <td style="text-align: center; vertical-align: middle;"> <image src = "../ScipyNumpy/CheatSheet/figures/slice-M[2:4,2:4].svg" width="59%"></image> </td>
        </tr>
        <tr>
            <td> <pre>M[::2, ::2] = 1</pre> </td>
            <td style="text-align: center; vertical-align: middle;"> <image src = "../ScipyNumpy/CheatSheet/figures/slice-M[::2,::2].svg" width="59%"></image> </td>
        </tr>
        <tr>
            <td> <pre>M[3::2, 3::2] = 1</pre> </td>
            <td style="text-align: center; vertical-align: middle;"> <image src = "../ScipyNumpy/CheatSheet/figures/slice-M[3::2,3::2].svg" width="59%"></image></td>
        </tr>
    </tbody>
</table>


## Operations on matrices

Start from a simple matrix:
```Python
rows, cols = 3, 6
M = np.linspace(0, 1, rows * cols).reshape(rows, cols)
```

<center>
<image src = "../ScipyNumpy/CheatSheet/figures/Operations-M.svg" width="25%"></image>
</center>

Starting from the previous matrix, we can apply the following operations:

<table>
  <thead>
    <tr>
      <th>Code</th>
      <th>Result</th>
    </tr>
  </thead>
  <tbody>
        <tr>
            <td> <pre> M.T </pre> </td>
            <td> <center><image src = "../ScipyNumpy/CheatSheet/figures/Operations-transposition.svg" width="24%"></image></center>  </td>
        </tr>
        <tr>
            <td> <pre> M[::-1, :] </pre> </td>
            <td> <center><image src = "../ScipyNumpy/CheatSheet/figures/Operations-from-end-row.svg" width="48%"></image></center>  </td>
        </tr>
        <tr>
            <td> <pre> M[:, ::-1] </pre> </td>
            <td> <center><image src = "../ScipyNumpy/CheatSheet/figures/Operations-from-end-col.svg" width="48%"></image></center>  </td>
        </tr>
        <tr>
            <td> <pre>np.where(M > 0.5, 0, 1) </pre> </td>
            <td> <center><image src = "../ScipyNumpy/CheatSheet/figures/Operations-where.svg" width="48%"></image></center>  </td>
        </tr>
        <tr>
            <td> <pre>np.maximum(M, 0.5) </pre> </td>
            <td> <center><image src = "../ScipyNumpy/CheatSheet/figures/Operations-max.svg" width="48%"></image></center>  </td>
        </tr>
        <tr>
            <td> <pre>np.minimum(M, 0.5) </pre> </td>
            <td> <center><image src = "../ScipyNumpy/CheatSheet/figures/Operations-min.svg" width="48%"></image></center>  </td>
        </tr>
        <tr>
            <td> <pre>np.mean(M, axis=0) </pre> </td>
            <td> <center><image src = "../ScipyNumpy/CheatSheet/figures/Operations-mean0.svg" width="48%"></image></center>  </td>
        </tr>
        <tr>
            <td> <pre>np.mean(M, axis=1) </pre> </td>
            <td> <center><image src = "../ScipyNumpy/CheatSheet/figures/Operations-mean1.svg" width="24%"></image> </center> </td>
        </tr>

    </tbody>
</table>


::: {.callout-note}

For the last operations note that the dimensions of the matrices are reduced, so you create a vector as a result, with dimensions `(6,)` or `(3,)` respectively, when computing the mean along the 0-axis (column-wise mean), respectively along the 1-axis (row-wise mean).
:::

## Broadcasting
Broadcasting allows the addition of matrices of different sizes (though this is mathematically wrong), by repeating the smaller ones along the missing dimensions. The only requirement is that the trailing (*i.e,* rightmost) dimensions match, somehow.

<table>
  <thead>
    <tr>
      <th>M</th>
      <th>N</th>
      <th>M+N</th>
    </tr>
  </thead>
  <tbody>
        <tr>
        <tr>
            <td style="text-align: center; vertical-align: middle;"> <image src = "../ScipyNumpy/CheatSheet/figures/Broadcast-M.svg" width="72%"></image> </td>
            <td> <center><image src = "../ScipyNumpy/CheatSheet/figures/Broadcast-scalar.svg" width="12%"></image> </center> </td>
            <td style="text-align: center; vertical-align: middle;"> <image src = "../ScipyNumpy/CheatSheet/figures/Broadcast-scalar-res.svg" width="72%"></image> </td>
        </tr>
        <tr>
            <td style="text-align: center; vertical-align: middle;"> <image src = "../ScipyNumpy/CheatSheet/figures/Broadcast-M.svg" width="72%"></image> </td>
            <td style="text-align: center; vertical-align: middle;"> <image src = "../ScipyNumpy/CheatSheet/figures/Broadcast-row.svg" width="72%"></image> </td>
            <td style="text-align: center; vertical-align: middle;"> <image src = "../ScipyNumpy/CheatSheet/figures/Broadcast-row-res.svg" width="72%"></image> </td>
        </tr>
        <tr>
            <td style="text-align: center; vertical-align: middle;"> <image src = "../ScipyNumpy/CheatSheet/figures/Broadcast-M.svg" width="72%"></image> </td>
            <td>  <center><image src = "../ScipyNumpy/CheatSheet/figures/Broadcast-col.svg" width="12%"></image> </center> </td>
            <td style="text-align: center; vertical-align: middle;"> <image src = "../ScipyNumpy/CheatSheet/figures/Broadcast-col-res.svg" width="72%"></image> </td>
        </tr>
        <tr>
            <td> <center><image src = "../ScipyNumpy/CheatSheet/figures/Broadcast-col2.svg" width="72%"></image></center> </td>
            <td>  <center><image src = "../ScipyNumpy/CheatSheet/figures/Broadcast-row2.svg" width="12%"></image> </center> </td>
            <td style="text-align: center; vertical-align: middle;"> <image src = "../ScipyNumpy/CheatSheet/figures/Broadcast-col-row.svg" width="72%"></image> </td>
        </tr>
    </tbody>
</table>

## Resources
- This work is deeply inspired and adapted from the great work by Nicolas Rougier: [https://github.com/rougier/numpy-tutorial](https://github.com/rougier/numpy-tutorial)
